cert:
  name: self-signed-clusterissuer     # name of the cert manager cluster issuer
  kind: ClusterIssuer

wordpress:
  allowEmptyPassword: false
  ingress:
    enabled: true
  service:
    type: ClusterIP        # rely on an ingress to serve traffic

  mariadb:
    enabled: false      # use RDS instead, except locally
    db:
      name: wordpress
      user: wordpress
