prometheus-operator:
  prometheus:
    ingress:
      enabled: true
      hosts:
      - {{ .kapp.vars.prometheusHostname }}
      tls:
        - hosts:
            - {{ .kapp.vars.prometheusHostname }}
          secretName: {{ .kapp.vars.release }}-cert

  grafana:
    ingress:
      enabled: true
      hosts:
      - {{ .kapp.vars.grafanaHostname }}
      tls:
        - hosts:
            - {{ .kapp.vars.grafanaHostname }}
          secretName: {{ .kapp.vars.release }}-cert

  alertmanager:
    ingress:
      enabled: true
      hosts:
      - {{ .kapp.vars.alertManagerHostname }}
      tls:
        - hosts:
            - {{ .kapp.vars.alertManagerHostname }}
          secretName: {{ .kapp.vars.release }}-cert

cert:
  kind: "{{ .kapp.vars.cert_manager_issuer_kind }}"
  name: "{{ .kapp.vars.cert_manager_issuer_name }}"
