apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: "{{ .Release.Namespace }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ required "No ca.crt specified" .Values.ca.crt  }}
  tls.key: {{ required "No ca.key specified" .Values.ca.key }}
