wordpress:
  ingress:
    enabled: true
    hosts:
      - name: {{ .kapp.vars.hostname }}
    tls:
      - hosts:
          - {{ .kapp.vars.hostname }}
        secretName: {{ .kapp.vars.release | default .kapp.id }}-tls

cert:
  kind: {{ .outputs.bootstrap__cert_manager.clusterIssuer.kind }}
  name: {{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}
