wordpress:
  ingress:
    enabled: true
    annotations:
      # use the ingress-shim annotation instead of an explicitly defined certificate
      "certmanager.k8s.io/cluster-issuer": {{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}
    hosts:
      - name: {{ .kapp.vars.hostname }}
    tls:
      - hosts:
          - {{ .kapp.vars.hostname }}
        secretName: {{ .kapp.vars.release }}-tls

nameOverride: {{ .kapp.vars.release }}
