prometheus:
  server:
    ingress:
      enabled: true
      hosts:
        - {{ .kapp.vars.release }}.{{ .cluster_name }}
      tls:
        - hosts:
            - {{ .kapp.vars.release }}.{{ .cluster_name }}
          secretName: {{ .kapp.vars.release }}-cert

cert:
  kind: {{ .outputs.bootstrap__cert_manager.clusterIssuer.kind }}
  name: {{ .outputs.bootstrap__cert_manager.clusterIssuer.metadata.name }}
