apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "prometheus-operator.name" . }}-cert
  labels:
    app: {{ template "prometheus-operator.name" . }}
    chart: {{ template "prometheus-operator.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  secretName: {{ template "prometheus-operator.name" . }}-cert
  issuerRef:
    name: {{ .Values.cert.name }}
    kind: {{ .Values.cert.kind }}
  commonName: {{ template "prometheus-operator.name" . }}
  dnsNames:
  - {{ template "prometheus-operator.name" . }}
  - {{ template "prometheus-operator.name" . }}.{{ .Release.Namespace }}
  - {{ template "prometheus-operator.name" . }}.{{ .Release.Namespace }}.svc
  - {{ template "prometheus-operator.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- if index .Values "prometheus-operator" "prometheus" "ingress" "tls" }}
  {{- range index .Values "prometheus-operator" "prometheus" "ingress" "tls" }}
    {{- range .hosts }}
  - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if index .Values "prometheus-operator" "grafana" "ingress" "tls" }}
  {{- range index .Values "prometheus-operator" "grafana" "ingress" "tls" }}
    {{- range .hosts }}
  - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if index .Values "prometheus-operator" "alertmanager" "ingress" "tls" }}
  {{- range index .Values "prometheus-operator" "alertmanager" "ingress" "tls" }}
    {{- range .hosts }}
  - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}