cert:
  name: ca-cluster-issuer     # name of the cert manager cluster issuer
  kind: ClusterIssuer

keycloak:
  keycloak:
    username: admin

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"

#     hosts:
#     - keycloak.example.com         # set by the Makefile

#      tls:
#      - hosts:
#        - keycloak.example.com         # set in _generated_values.yaml file because
#        secretName: keycloak-cert      # lists of maps can't currently be `helm --set` (GH #4508)

# todo - create an example of importing data on boot to initialise local/dev clusters.
# See: https://www.keycloak.org/docs/2.5/server_admin/topics/export-import.html
#    extraVolumes: |
#      - name: realm-secret
#        secret:
#          secretName: realm-secret
#
#    extraVolumeMounts: |
#      - name: realm-secret
#        mountPath: "/realm/"
#        readOnly: true

#    extraArgs: -Dkeycloak.import=/realm/realm.json
