keycloak:
  keycloak:
    username: admin

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"

# todo - create an example of importing data on boot to initialise local/dev clusters.
# See: https://www.keycloak.org/docs/2.5/server_admin/topics/export-import.html
#    extraVolumes: |
#      - name: realm-secret
#        secret:
#          secretName: realm-secret
#
#    extraVolumeMounts: |
#      - name: realm-secret
#        mountPath: "/realm/"
#        readOnly: true

#    extraArgs: -Dkeycloak.import=/realm/realm.json
