nginx-ingress:
  controller:
    service:
      type: NodePort
      externalTrafficPolicy: Local
      enableHttp: false           # Disable HTTP traffic. Only HTTPS traffic will be served

    config:
      server-tokens: "false"
