apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "jenkins.name" . }}-cert
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.jenkins.master.componentName }}"
spec:
  secretName: {{ template "jenkins.name" . }}-cert
  issuerRef:
    name: {{ .Values.cert.name }}
    kind: {{ .Values.cert.kind }}
  commonName: {{ template "jenkins.name" . }}
  dnsNames:
  - {{ template "jenkins.name" . }}
  - {{ template "jenkins.name" . }}.{{ .Release.Namespace }}
  - {{ template "jenkins.name" . }}.{{ .Release.Namespace }}.svc
  - {{ template "jenkins.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- if .Values.jenkins.master.ingress.tls }}
  {{- range .Values.jenkins.master.ingress.tls }}
    {{- range .hosts }}
  - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}