jenkins:
  master:
    serviceType: NodePort
    installPlugins:
      - prometheus:2.0.4

  networkPolicy:
    enabled: true

  prometheus:
    operator:
      namespace: prometheus-operator
      alertmanager: alertmanager

serviceAccount:
  create: true
