jenkins:
  master:
    serviceType: NodePort

  networkPolicy:
    enabled: true

  prometheus:
    operator:
      namespace: prometheus-operator
      alertmanager: alertmanager

serviceAccount:
  create: true
