keycloak:
  keycloak:
    ingress:
      hosts:
        - {{ .kapp.vars.release }}.{{ .cluster_name }}
    tls:
      - hosts:
          - {{ .kapp.vars.release }}.{{ .cluster_name }}
        secretName: {{ .kapp.vars.release }}-cert

cert:
  name: {{ .outputs.bootstrap__nginx_ingress.values.cert.name }}
  kind: {{ .outputs.bootstrap__nginx_ingress.values.cert.kind }}
