keycloak:
  keycloak:
    ingress:
      annotations:
        "kubernetes.io/ingress.class": {{ .kapp.vars.ingress_class }}
      hosts:
        - "{{ .kapp.vars.hostname }}"
      tls:
        - hosts:
            - "{{ .kapp.vars.hostname }}"
          secretName: {{ .kapp.vars.release }}-cert

cert:
  kind: "{{ .kapp.vars.cert_manager_issuer_kind }}"
  name: "{{ .kapp.vars.cert_manager_issuer_name }}"
