# from https://docs.helm.sh/using_helm
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: {{namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: {{namespace}}
